### ISSUE TITLE
generovanie

### ISSUE THREAD

**Issue by Jaro450** [VasaMM/OSM-Garmin-Maps-by-VasaM#15]
Directory userAreas already exists
The name of the output folder with garmin maps (default maps):
The name of the folder for map data download (default pbf):
The name of the folder for polygons (default polygons):
The name of the folder for height data (default hgt):
The name of the folder for temporary data (default temp):
The name of the folder for sea data (default sea):
The name of the folder for bounds data (default bounds):
Stahuji 'http://osm.thkukuk.d.../sea-latest.zip'   272 MB
100%  [==============================]  272 MB / 272 MB   0.0 MB/s   eta 0      
Stahuji 'http://osm.thkukuk.d...unds-latest.zip'   1199 MB
100%  [==============================]  1199 MB / 1199 MB   901.71 MB/s   eta 0 s           
Download splitter version 610
Stahuji 'https://www.mkgmap.o...litter-r610.zip'   1 MB
100%  [==============================]  1 MB / 1 MB   0.0 MB/s   eta 0      
Unzip
Download mkgmap version 4793
Stahuji 'https://www.mkgmap.o...kgmap-r4793.zip'   3 MB
100%  [==============================]  3 MB / 3 MB   0.0 MB/s   eta 0      
Unzip
Detected system Linux 64bit
Download osmconvert for this system
Stahuji 'http://m.m.i24.cc/osmconvert64'   0 MB
100%  [==============================]  0 MB / 0 MB   0.0 MB/s   eta 0

osmconvert64 stiahne, má to 245,9 KiB 
ale tam to skončí. 
ako správne generovať mapy?
myAreas.py sa nedá prepísať
keď dám
python ./gmapmaker.py -a <area>
Keď dám SK alebo Slovensko 
chyba syntaxe neďaleko neočakávaného tokenu „newline“

**Comment by VasaMM** [comment]
To je divné.  Můžeš poslat screenshot konzole, aby bylo vidět, co přesně jsi zadal a co to vypsalo?

**Comment by Jaro450** [comment]
ospravedlňujem sa, dobehla ma choroba vo forme hypoglikémie .
Nakoniec som to zvládol.
Problém bol vo verziách mkgmap a splitter

ďalší bol v:jaro@debian:~/osm$ python gmapmaker.py --version
Traceback (most recent call last):
  File "gmapmaker.py", line 6, in <module>
    from makerfuncs import *
  File "/home/jaro/osm/makerfuncs/args.py", line 48
SyntaxError: Non-ASCII character '\xc3' in file /home/jaro/osm/makerfuncs/args.py on line 48, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

vyriešené, nemal som nainštalovanú angličtinu, vyriešil som doinštalovaním eng a cz 

ďakujem

**Comment by VasaMM** [comment]
Takže nyní vše funguje? Ten non-ASCII znak zkontroluju a vyhodím pryč.

**Comment by Jaro450** [comment]
Ano
Ďakujem

**Comment by VasaMM** [comment]
Vyřešeno
