### ISSUE TITLE
area

### ISSUE THREAD

**Issue by Jaro450** [VasaMM/OSM-Garmin-Maps-by-VasaM#20]
nerád ruším ale asi už naposledy
ako je to s Ruskom? Konkrétne s oblasťami.
Nie je mi jasné ako zadať danú oblasť
python3 gmapmaker.py -a RU --area Moskva
[INFO] Spusteno v 2021-09-09 11:50:40.105387
[INFO] Dekoduji oblast Moskva
[ERROR] Neplatna oblast Moskva

je niekde zoznam oblastí?

dík moc

**Comment by VasaMM** [comment]
Ahoj,
prvně příkazy `-a` a `--area` jsou identické a očekávají kód oblasti (RU). Pokud není zadán, bude uživateli nabídnut seznam všech oblastí.
Ten je popsán [zde](https://github.com/VasaMM/OSM-Garmin-Maps-by-VasaM#seznam-st%C3%A1t%C5%AF).

Bohužel jsem zjistil, že Rusko je trochu problém, takže jsem jej musel přidat jako nový kontinent. Stačí ti stáhnout soubor makerfuncs/states.py. Rusko je přidáno na konci. Jinak Moskvu jsem nechal generovat, měla by se časem objevit na webu.

**Comment by Jaro450** [comment]
dík moc, je to funkčné. dnes som skúsil RU-SZFO
ale nebolo to bez chýb
N80E062: using existing file hgt/VIEW3/N80E062.hgt.
N81E062: trying view3 ...
N81E062: using existing file hgt/VIEW3/N81E062.hgt.
N82E062: trying view3 ...
N82E062: no file found on server.
N66E063: trying view3 ...
N66E063: using existing file hgt/VIEW3/N66E063.hgt.
N67E063: trying view3 ...
N67E063: using existing file hgt/VIEW3/N67E063.hgt.
N68E063: trying view3 ...
N68E063: using existing file hgt/VIEW3/N68E063.hgt.
N69E063: trying view3 ...
N69E063: using existing file hgt/VIEW3/N69E063.hgt.
N70E063: trying view3 ...
N70E063: no file found on server.
N71E063: trying view3 ...
N71E063: no file found on server.
N72E063: trying view3 ...
N72E063: no file found on server.
N73E063: trying view3 ...
N73E063: no file found on server.
N74E063: trying view3 ...
N74E063: no file found on server.

mapa sa vygenerovala a je funkčná. Predpokladám, že sa jedná o vojenské oblasti a takýto problém bude v RU bežný.

**Comment by VasaMM** [comment]
Když se podíváš, kam souřadnice ukazují, jedná se o oblasti v moři. K těm nejsou výšková data, takže se správně doplní výška 0.
