### ISSUE TITLE
chyba

### ISSUE THREAD

**Issue by Jaro450** [VasaMM/OSM-Garmin-Maps-by-VasaM#24]
ahoj
ospravedlňujem sa ale vyskytla sa chyba aj keď som nič nerobil. Je fakt, že sa to pohnojilo pri výpadku prúdu keď som generoval mapu. java -Xmx2g -jar je jedno ako nastavím, chyba sa objavý

[RUN] java -Xmx2g -jar ./mkgmap-r0/mkgmap.jar -c ./garmin-style/mkgmap-settings.conf --bounds=bounds/ --precomp-sea=sea/sea/ --dem=hgt/VIEW3/ --max-jobs=4 --mapname="72150001" --overview-mapnumber="72150000" --family-id="7215" --description="Slovensko_VasaM" --family-name="Slovensko_VasaM" --series-name="Slovensko_VasaM" --area-name="Slovensko_VasaM" --country-name="Slovensko_VasaM" --country-abbr="SK" --region-name="Slovensko_VasaM" --region-abbr="SK" --product-version=101 --output-dir=maps/SK_VasaM --dem-poly=polygons/SK.poly --license-file=temp/license.txt --code-page=1250 pbf/SK-SPLITTED/*.osm.pbf pbf/SK-SPLITTED-SRTM/*.osm.pbf ./garmin-style/style.txt
[ERROR] stderr: Error: Unable to access jarfile ./mkgmap-r0/mkgmap.jar

[ERROR] java -Xmx2g -jar ./mkgmap-r0/mkgmap.jar -c ./garmin-style/mkgmap-settings.conf --bounds=bounds/ --precomp-sea=sea/sea/ --dem=hgt/VIEW3/ --max-jobs=4 --mapname="72150001" --overview-mapnumber="72150000" --family-id="7215" --description="Slovensko_VasaM" --family-name="Slovensko_VasaM" --series-name="Slovensko_VasaM" --area-name="Slovensko_VasaM" --country-name="Slovensko_VasaM" --country-abbr="SK" --region-name="Slovensko_VasaM" --region-abbr="SK" --product-version=101 --output-dir=maps/SK_VasaM --dem-poly=polygons/SK.poly --license-file=temp/license.txt --code-page=1250 pbf/SK-SPLITTED/*.osm.pbf pbf/SK-SPLITTED-SRTM/*.osm.pbf ./garmin-style/style.txt vratil 1 (ocekavana 0)
[INFO] Ukonceno v 2021-09-20 11:00:12.111055, doba behu 0:25:19.381917

**Comment by Jaro450** [comment]
prepáč, popátral som a zistil chybu
poškodený mkgmap
už všetko OK
dík

**Comment by VasaMM** [comment]
Chyby, které se sami vyřeší mám nejraději :-).
