### ISSUE TITLE
Error: input file doesn't exist or is not a readable file: ./pbf/OL-SRTM.osm.pbf

### ISSUE THREAD

**Issue by pschonmann** [VasaMM/OSM-Garmin-Maps-by-VasaM#6]
Ahoj, behem generovani skriptu jsem si vsiml ze se asi deje neco spatnyho s vrstevnicema :) Viz titulek.
Vrstevnice jsou generovany. Viz vypis adresare

d:\openstreetmap\OSM-Garmin-Maps-by-VasaM\pbf>dir /b
AD-SPLITTED
AD-SRTM_lon1.41_1.79lat42.43_42.66_view3.osm.pbf
AD.osm.pbf
OL-SPLITTED
OL-SRTM_lon17.10_17.50lat49.50_49.70_view3.osm.pbf
OL.osm.pbf
README.md

PS: chtelo by to do navodu dopsat nove zavislosti :)

**Comment by pschonmann** [comment]
[INFO] Start at 2020-04-12 17:03:54.185799
[INFO] Area id: OL
[INFO] Data id: OL
[INFO] File OL.osm.pbf found
[INFO] Generate contour line
[ERROR] Cann't generate contour lines!
[INFO] Making map for garmin...
[INFO] Konec v 2020-04-12 17:04:18.376920, beh 0:00:24.191121

**Comment by VasaMM** [comment]
Na cestě je nový skript, viz _dev_ větev, a tam jsem práci s vrstevnicemi opravoval.
